name: cogni_anchor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^11.3.0
  flutter_image_compress: ^2.2.0
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: 0.12.1
  image: ^4.1.3
  http: ^1.6.0
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+5
  flutter_bloc: ^9.1.1
  intl: ^0.20.2
  supabase_flutter: ^2.5.6
  flutter_local_notifications: ^19.5.0
  timezone: ^0.10.1
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  google_fonts: ^6.1.0  
  flutter_sound: ^9.2.13 
  audioplayers: ^5.2.1 
  path_provider: ^2.1.2 


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite
