name: cogni_anchor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.10.6
  google_mlkit_face_detection: ^0.11.0
  tflite_flutter: 0.12.1
  image: ^4.1.3
  http: ^0.13.6
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: 4.0.4
  cupertino_icons: ^1.0.8
  google_nav_bar: ^5.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/models/mobilefacenet.tflite
